In [1]:
# Data Analysis
import pandas as pd

# Data Visualization
from matplotlib import pyplot as plt
from matplotlib.figure import Figure

# Utilities
import numpy as np
import math
import Constants as const
from sklearn import linear_model
from sklearn.impute import KNNImputer

# print(const.const_dict["MMSE_MAX"])

In [2]:
#Load dataset
df = pd.read_excel('TrainingSet.xlsx')
# df = pd.read_excel('TestSet.xlsx')
df

,ID,CAP,Scolarita,Eta,Sesso,MMSE_PG,MMSE_PC,MMSE_PE,MMSE_ESITO,CLOCKTEST_PG,...,FAB_PE,FAB_ESITO,FLUENZAVERBFON_PG,FLUENZAVERBFON_PC,FLUENZAVERBFON_PE,FLUENZAVERBFON_ESITO,TESTMATRICIATTENTIVE_PG,TESTMATRICIATTENTIVE_PC,TESTMATRICIATTENTIVE_PE,TESTMATRICIATTENTIVE_ESITO
0,Row6,80059,13.0,81.0,M,25.0,25.00,238.0,NORMA,7.0,...,1203.0,NORMA,14.0,13.5,0.0,DEFICIT,52.0,52.50,4.0,NORMA
1,Row8,80030,5.0,76.0,F,24.0,26.03,238.0,NORMA,4.0,...,1203.0,NORMA,14.0,23.4,2.0,NORMA,NaN,NaN,NaN,NaN
2,Row9,84018,8.0,66.0,F,28.0,28.53,238.0,NORMA,7.0,...,NaN,NaN,20.0,23.2,2.0,NORMA,38.0,NaN,2.0,NORMA
3,Row10,84018,10.0,62.0,F,27.0,26.49,238.0,NORMA,7.0,...,NaN,NaN,41.0,43.5,4.0,NORMA,40.0,39.25,2.0,NORMA
4,Row13,80054,14.0,59.0,F,25.0,23.31,238.0,LIMITI,0.0,...,1203.0,NORMA,32.0,27.8,3.0,NORMA,38.0,34.00,1.0,AI LIMITI INFERIORI DELLA NORMA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Row505,80058,5.0,80.0,f,8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Row506,80040,8.0,72.0,M,25.0,26.20,238.0,NORMA,9.0,...,1203.0,NORMA,23.0,26.9,3.0,NORMA,37.0,36.50,1.0,AI LIMITI INFERIORI DELLA NORMA
161,Row507,80040,13.0,77.0,F,29.0,28.86,238.0,NORMA,7.0,...,1203.0,NORMA,27.0,25.5,3.0,NORMA,52.0,53.75,4.0,NORMA
162,Row508,80100,17.0,62.0,M,29.0,27.46,238.0,NORMA,10.0,...,1203.0,NORMA,48.0,40.2,4.0,NORMA,55.0,46.00,3.0,NORMA
163,Row509,80058,13.0,68.0,F,27.0,26.49,238.0,NORMA,1.0,...,1203.0,NORMA,35.0,31.9,4.0,NORMA,47.0,45.75,3.0,NORMA

In [3]:
# Convert Sex attribute in UpperCase
df['Sesso'] = df['Sesso'].str.upper()

# Remove CAP attribute
df = df.drop(columns =['CAP'])

# Remove unlabeled instances
df = df.loc[df["Patologia"] == df["Patologia"]]

dim_df = len(df['ID'])

In [4]:
df_clean = pd.DataFrame(columns = df.columns[0:4], data = df.iloc[:,0:4])
df_clean

         ID  Scolarita   Eta Sesso
0      Row6       13.0  81.0     M
1      Row8        5.0  76.0     F
2      Row9        8.0  66.0     F
3     Row10       10.0  62.0     F
4     Row13       14.0  59.0     F
..      ...        ...   ...   ...
159  Row505        5.0  80.0     F
160  Row506        8.0  72.0     M
161  Row507       13.0  77.0     F
162  Row508       17.0  62.0     M
163  Row509       13.0  68.0     F

[164 rows x 4 columns]

In [5]:
def lin_reg(feature, scolarita, eta, raw_score):
    # Create linear regression object
    regr = linear_model.LinearRegression(normalize = True)
    # Train the model using the training sets
    df_test = df.loc[(df["Scolarita"] == df["Scolarita"]) & (df["Eta"] == df["Eta"]) & (df[feature+"_PG"] == df["MMSE_PG"]) & (df[feature+"_PC"] == df[feature+"_PC"])]
    df_temp = pd.DataFrame(columns = ["Scolarita", "Eta", feature+"_PG"])
    df_temp["Scolarita"] = df_test["Scolarita"]
    df_temp["Eta"] = df_test["Eta"]
    df_temp[feature+"_PG"] = df_test[feature+"_PG"]

    regr.fit(df_temp.values, df_test[feature+"_PC"])

    # Make predictions using the testing set
    res = regr.predict([[scolarita, eta, raw_score]])
    return res

In [6]:
def new_column(df, df_clean, feature):
    col_pc = feature + '_PC'
    col_pg = feature + '_PG'
    col_es = feature + '_ESITO'
    col_new = feature
    tresh = const.const_dict["TRESHOLD"]

    for i in range(dim_df):

        if col_pc in df.columns:

            if (df.loc[i, col_pc] == df.loc[i, col_pc]) and (df.loc[i,col_pg] == df.loc[i,col_pg]):
                if abs(df.loc[i, col_pc] - df.loc[i,col_pg]) < tresh:
                    df_clean.loc[i,col_new] = df.loc[i, col_pc]
                else:
                    df_clean.loc[i,col_new] = df.loc[i, col_pg] #----REG

            elif (df.loc[i, col_pc] != df.loc[i, col_pc]) and (df.loc[i,col_pg] == df.loc[i,col_pg]):
                df_clean.loc[i,col_new] = df.loc[i, col_pg] 
            elif (df.loc[i, col_pc] == df.loc[i, col_pc]) and (df.loc[i,col_pg] != df.loc[i,col_pg]):
                df_clean.loc[i,col_new] = df.loc[i, col_pc]

            elif df.loc[i,col_es] == df.loc[i,col_es]:
                if df.loc[i,col_es] == "NORMA":
                    df_clean.loc[i,col_new] = (const.const_dict[col_new + "_MAX"] + const.const_dict[col_new + "_CUTOFF"])/2
                elif df.loc[i,col_es] == "DEFICIT":
                    df_clean.loc[i,col_new] = const.const_dict[col_new + "_CUTOFF"]/2
                else:
                    df_clean.loc[i,col_new] = const.const_dict[col_new + "_CUTOFF"]

            # else:
                #Null

        else:
            if df.loc[i,col_pg] == df.loc[i,col_pg]:
                df_clean.loc[i,col_new] = df.loc[i, col_pg] #-----REG
                
            elif df.loc[i,col_es] == df.loc[i,col_es]:
                if df.loc[i,col_es] == "NORMA":
                    df_clean.loc[i,col_new] = (const.const_dict[col_new + "_MAX"] + const.const_dict[col_new + "_CUTOFF"])/2
                elif df.loc[i,col_es] == "DEFICIT":
                    df_clean.loc[i,col_new] = const.const_dict[col_new + "_CUTOFF"]/2
                else:
                    df_clean.loc[i,col_new] = const.const_dict[col_new + "_CUTOFF"]
            # else:
                #Null

# plt.hist(df_clean['MMSE'], bins = 20)

In [7]:
# "Feature selection"
new_column(df, df_clean, "MMSE")
new_column(df, df_clean, "CLOCKTEST")
new_column(df, df_clean, "COPIAFIGURAREY")
new_column(df, df_clean, "PAROLEREYIMM")
new_column(df, df_clean, "PAROLEREYDIFF")
new_column(df, df_clean, "MEMORIAFIGURAREY")
new_column(df, df_clean, "FAB")
new_column(df, df_clean, "FLUENZAVERBFON")
new_column(df, df_clean, "TESTMATRICIATTENTIVE")

In [8]:
# df_clean.to_excel("excel.xlsx")
# Missing Value Imputation
imputer = KNNImputer()

# fit on the dataset
imputer.fit(df_clean.drop(["ID", "Sesso"], axis = 1))

# transform the dataset
imp = imputer.transform(df_clean.drop(["ID", "Sesso"], axis = 1))
imp

array([[13.   , 81.   , 25.   , ..., 14.   , 13.5  , 52.5  ],
       [ 5.   , 76.   , 26.03 , ...,  9.   , 23.4  , 42.75 ],
       [ 8.   , 66.   , 28.53 , ..., 15.828, 23.2  , 38.   ],
       ...,
       [13.   , 77.   , 28.86 , ..., 18.   , 25.5  , 53.75 ],
       [17.   , 62.   , 27.46 , ..., 18.   , 40.2  , 46.   ],
       [13.   , 68.   , 26.49 , ..., 17.   , 31.9  , 45.75 ]])

In [9]:
df_imp = pd.DataFrame(columns = df_clean.drop(["ID", "Sesso"], axis = 1).columns, data = imp)

df_imp.insert(0, "ID", df_clean["ID"].values)
df_imp.insert(len(df_imp.columns), "Patologia", df['Patologia'].values)

df_imp.to_csv("ImputationParziale.csv", index = False)
# df_imp.to_csv("ImputationParzialeTest.csv", index = False)